version: "3.9"

services:

  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: python scripts/cli.py --cities cairo dubai --days 3 --output data/compose_test.csv

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    volumes:
      - ./data:/app/data
      - ./weather_dbt:/app/weather_dbt
